version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying files to S3...
      - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
